package main

import (
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"deanprice.com/internal/cipher"
	"deanprice.com/internal/defaults"
)

const defaultMasterSeed uint64 = 0x123456789abcdef0
const targetDomain = "deanprice.com"

func getMasterSeed() uint64 {
	envSeed := strings.TrimSpace(os.Getenv("SECRET_SEED"))
	envSeed = strings.TrimSpace(strings.Trim(envSeed, `"'`))
	if envSeed != "" {
		val, err := strconv.ParseUint(envSeed, 0, 64)
		if err != nil {
			log.Fatalf("FATAL: SECRET_SEED is set but invalid (%q): %v", envSeed, err)
		}
		return val
	}
	return defaultMasterSeed
}

func encode(text string, nonce string, seed uint64, withType bool) string {
	if text == "" {
		if withType {
			return "[]byte(nil)"
		}
		return "nil"
	}

	encrypted := cipher.Crypt([]byte(text), seed, targetDomain, "load", nonce)
	strVals := make([]string, len(encrypted))
	for i, b := range encrypted {
		strVals[i] = strconv.Itoa(int(b))
	}

	prefix := ""
	if withType {
		prefix = "[]byte"
	}
	return prefix + "{" + strings.Join(strVals, ", ") + "}"
}

func processEmail(e string, seed uint64) string {
	e = strings.TrimSpace(e)
	if e == "" {
		return encode("", "email", seed, true)
	}
	if !strings.HasPrefix(e, "mailto:") {
		e = "mailto:" + e
	}
	return encode(e, "email", seed, true)
}

func processPhone(phone string, region string, seed uint64) string {
	phone = strings.TrimSpace(phone)
	if phone == "" {
		return encode("", "phone_"+region, seed, false)
	}
	if !strings.HasPrefix(phone, "tel:") {
		if !strings.HasPrefix(phone, "+") {
			phone = "+" + phone
		}
		phone = "tel:" + phone
	}
	return encode(phone, "phone_"+region, seed, false)
}

func processWA(wa string, region string, seed uint64) string {
	cleanNum := defaults.CleanDigits(wa)
	if cleanNum == "" {
		return encode("", "wa_"+region, seed, false)
	}
	return encode("https://wa.me/"+cleanNum, "wa_"+region, seed, false)
}

func generateData(cfg Config) error {
	seed := getMasterSeed()

	branch := os.Getenv("CF_PAGES_BRANCH")
	isCFPagesProd := os.Getenv("CF_PAGES") != "" && (branch == "main" || branch == "")
	isProdCI := isCFPagesProd || os.Getenv("PRODUCTION") != "" || os.Getenv("STRICT_SEEDS") != "" || (os.Getenv("CI") != "" && os.Getenv("GITHUB_ACTIONS") == "")
	if isProdCI {
		if seed == defaultMasterSeed {
			log.Fatal("FATAL: SECRET_SEED must be configured in CI/production builds.")
		}
		if os.Getenv("SECRET_EMAIL") == "" {
			log.Fatal("FATAL: SECRET_EMAIL must be configured in CI/production builds.")
		}
		if os.Getenv("SECRET_PHONE_GB") == "" || os.Getenv("SECRET_PHONE_IE") == "" || os.Getenv("SECRET_PHONE_TR") == "" {
			log.Fatal("FATAL: Regional phone secrets (SECRET_PHONE_GB, SECRET_PHONE_IE, SECRET_PHONE_TR) must be configured in CI/production builds.")
		}
	}

	out := fmt.Sprintf(`// Code generated by tools. DO NOT EDIT.
package contact

func init() {
	masterSeed = 0x%x

	emailBytes = %s

	phoneMap = map[string][]byte{
		"GB": %s,
		"IE": %s,
		"TR": %s,
	}

	waMap = map[string][]byte{
		"GB": %s,
		"IE": %s,
		"TR": %s,
	}
}
`,
		seed,
		processEmail(cfg.Email, seed),
		processPhone(cfg.PhoneGB, "GB", seed), processPhone(cfg.PhoneIE, "IE", seed), processPhone(cfg.PhoneTR, "TR", seed),
		processWA(cfg.PhoneGB, "GB", seed), processWA(cfg.PhoneIE, "IE", seed), processWA(cfg.PhoneTR, "TR", seed),
	)

	formatted, err := format.Source([]byte(out))
	if err != nil {
		return fmt.Errorf("failed to format generated data.go: %w", err)
	}

	targetPath := filepath.Join("internal", "contact", "data.go")
	err = os.WriteFile(targetPath, formatted, 0644)
	if err != nil {
		return fmt.Errorf("failed to write %s: %w", targetPath, err)
	}
	fmt.Printf("Successfully generated domain-locked and fully salted %s (seed: 0x%x)\n", targetPath, seed)

	return nil
}
